### ISSUE TITLE
fix(sample/browser): TypeError: Reflect.get called on non-object

### ISSUE THREAD

**Issue by petermetz** [mattrglobal/bbs-signatures#49]
## To reproduce:
1. Clone my fork's branch (#48) that has the key pair generation function names fixed (otherwise the sample will stop working there)
2. Run the browser samples as instructed by the readme file under `./sample/browser`
3. Observe the crash

## Chrome Dev Tools Logs:

```sh
localhost/:1 Uncaught (in promise) Error(JsValue(TypeError: Reflect.get called on non-object
TypeError: Reflect.get called on non-object
    at Object.get (<anonymous>)
    at Module.eval (webpack:////home/peter/a/blockchain/bbs-signatures/pkg/index_bg.js?:644:23)
    at Module.eval (webpack:////home/peter/a/blockchain/bbs-signatures/pkg/index_bg.js?:451:22)
    at __wbg_get_2e96a823c1c5a5bd (http://localhost:8080/bbs-signatures.min.js:149:102)
    at js_sys::Reflect::get::hdb44b494eb45724a (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[1000]:0x1b98b7)
    at js_sys::try_iter::hb9f6985e5939da27 (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[260]:0x155380)
    at <serde_wasm_bindgen::de::Deserializer as serde::de::Deserializer>::deserialize_seq::h8a61401663b55dff (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[335]:0x1665a5)
    at serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::h1a24def40ef00233 (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[5448]:0x240a27)
    at <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hbf6636bd759ab427 (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[5478]:0x24107b)
    at <serde_wasm_bindgen::de::SeqAccess as serde::de::SeqAccess>::next_element_seed::h2d960dcb668c8169 (http://localhost:8080/294ad96f2bf83bcad951.module.wasm:wasm-function[354]:0x16a3fc)))
```

## With Dev Tools "Pause on Exception" this is where it goes sideways:

![image](https://user-images.githubusercontent.com/1583231/92514297-81b28380-f1c6-11ea-901d-c4ca3dca9adb.png)

**Comment by tplooker** [comment]
Addressed in #48

**Comment by petermetz** [comment]
> Addressed in #48

@tplooker Sorry, I may not have been entirely clear here in the description. This issue is not resolved by #48 but is rather unmasked by it. E.g., in my quest to make the sample work, I first encountered the function name issue (which I fixed) and then *afterwards* I hit the issue described here (and did not immediately know what the cause might be so I just opened this bug).

**Comment by tplooker** [comment]
Apologies @petermetz thanks for the clarification

**Comment by tplooker** [comment]
@petermetz on further investigation this issue is being caused by the change in the data type for messages member in the sign request from `string[]` to `Uint8Array[]` as reported in the [latest release](https://github.com/mattrglobal/bbs-signatures/blob/master/CHANGELOG.md#040-2020-08-27) see #40 for the PR that made the change

**Comment by tplooker** [comment]
See the [latest tests](https://github.com/mattrglobal/bbs-signatures/blob/master/tests/bbsSignature/sign.bbsSignature.spec.ts#L114) for an example on how to update them

**Comment by petermetz** [comment]
> See the [latest tests](https://github.com/mattrglobal/bbs-signatures/blob/master/tests/bbsSignature/sign.bbsSignature.spec.ts#L114) for an example on how to update them

Thanks @tplooker that helped a lot. Sent a PR with the sample fixed in it.

**Comment by tplooker** [comment]
Thanks @petermetz! Appreciate the contribution.
